module ShelbyArenaKeys
  USERNAME = '*** YOUR CHURCH USERNAME ***'
  PASSWORD = '*** YOUR CHURCH USER PASSWORD' 

  REGULAR_API_KEY = '*** REGULAR API KEY ***'
  REGULAR_API_SECRET = '*** REGULAR API SECRET ***'

  CONTRIBUTION_API_KEY = '*** CONTRIBUTION API KEY ***'
  CONTRIBUTION_API_SECRET = '*** CONTRIBUTION API SECRET ***'  

  SHELBY_ARENA_SERVICE_URL = '*** SERVICE URL ***'    
end
